#Create a new user
POST http://localhost:3003/api/auth/register HTTP/1.1
Content-Type: application/json

{
  "email": "SirBl@notfound.local",
  "name": "Sirius Black",
  "password": "123456"
}

###

# Get user by ID
GET http://localhost:3003/api/auth/64d54d69a1cadf5886c4dd9b HTTP/1.1

###

# Login user by email and password
POST http://localhost:3003/api/auth/login HTTP/1.1
Content-Type: application/json

{
  "email": "SirBl@notfound.local",
  "password": "123456"
}

###
